#!/bin/bash

echo "🚀 EJECUTAR CAPTURA EN VPS Y TRAER CONFIGURACIONES"
echo "=================================================="
echo ""

echo "📋 INSTRUCCIONES PARA EJECUTAR:"
echo "==============================="
echo ""
echo "1️⃣ CONECTAR AL VPS:"
echo "   ssh root@162.254.37.42"
echo ""
echo "2️⃣ IR AL PROYECTO:"
echo "   cd /var/www/html"
echo ""
echo "3️⃣ HACER PULL DE LA RAMA PRODUCTION:"
echo "   git checkout production-stable"
echo "   git pull origin production-stable"
echo ""
echo "4️⃣ EJECUTAR CAPTURA:"
echo "   chmod +x vps-capture-production-state.sh"
echo "   ./vps-capture-production-state.sh"
echo ""
echo "5️⃣ SUBIR CONFIGURACIONES CAPTURADAS:"
echo "   git add production-configs/"
echo "   git commit -m \"Add VPS production configurations - $(date)\""
echo "   git push origin production-stable"
echo ""
echo "6️⃣ AQUÍ EN LOCAL, HACER PULL:"
echo "   git checkout production-stable"
echo "   git pull origin production-stable"
echo ""
echo "📁 RESULTADO:"
echo "============="
echo "Tendrás todas las configuraciones del VPS en:"
echo "  📁 production-configs/nginx/"
echo "  📁 production-configs/pm2/"
echo "  📁 production-configs/env/"
echo "  📄 production-configs/PRODUCTION-STATE.md"
echo ""
echo "🔄 DESPUÉS CREAR RAMA DEVELOPMENT:"
echo "=================================="
echo "   git checkout development"
echo "   git merge production-stable"
echo "   git push origin development"
echo ""
echo "✅ Esto te dará una copia exacta del estado funcionando del VPS"
echo "   para trabajar en desarrollo sin romper producción."