#!/bin/bash
echo "🔍 Verificando actualización..."
echo ""
echo "1. Testing build..."
npm run build && echo "✅ Build OK" || echo "❌ Build failed"
echo ""
echo "2. Testing lint..."
npm run lint && echo "✅ Lint OK" || echo "❌ Lint failed"
echo ""
echo "3. Testing type check..."
npm run type-check && echo "✅ Types OK" || echo "❌ Types failed"
echo ""
echo "4. Dependencias finales:"
npm outdated || echo "✅ Todo actualizado"
